name: Publish Shiny App

on:
  push:
    branches: [main, master]  # Run on pushes to main or master
  workflow_dispatch:          # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v4

    # Step 2: Set up R
    - name: Set up R
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages:
          cran::shinylive@0.2.0 ## Pin version to ensure consistency

    # Step 3: Install Shinylive
    - name: Install Shinylive
      run: |
        Rscript -e 'install.packages("shinylive")'

    # Step 4: Export Shiny app as a static website
    - name: Export Shiny app
      run: |
        Rscript -e 'shinylive::export(".", "_site")'

    # Step 5: Upload artifact for deployment
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: _site
        retention-days: 1

    # Step 6: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2

